In [1]:
#지도시각화
import pandas as pd
import numpy as np
import folium

In [2]:
#hermes
hermes_geo = pd.read_csv('hermes_geo.shp.csv', encoding = 'cp949', engine = 'python')
hermes_geo.head()

,No,Unnamed: 1,No.1,store,address,경도,위도,상태
0,1,0,1,에르메스 신라면세점 제주점,제주특별자치도 제주시 노연로 69,126.487577,33.486285,정좌표
1,2,1,2,에르메스 신세계면세점 인천공항 2터미널점,인천광역시 중구 공항로 272,126.449106,37.457537,정좌표
2,3,2,3,에르메스 신세계면세점 인천공항 1터미널점,인천광역시 중구 공항로 272,126.449106,37.457537,정좌표
3,4,3,4,에르메스 신세계면세점 명동점,서울특별시 중구 퇴계로 77,126.980776,37.560360,정좌표
4,5,4,5,에르메스 롯데면세점 명동 본점,서울특별시 중구 을지로 30,126.981008,37.565346,정좌표

In [3]:
map_hermes = folium.Map(location = [36.7219941, 127.4959787], tiles = 'cartodbpositron', zoom_start = 6)

In [4]:
for i, store in hermes_geo.iterrows() :
    folium.Marker(location = [store['위도'], store['경도']],
                  tooltip = store['store'],
                  icon = folium.Icon(color = 'orange', icon = 'gift', prefix = 'fa')).add_to(map_hermes)

map_hermes.save('map_hermes.html')    
map_hermes

In [39]:
#louis vuitton
lv_geo = pd.read_csv('lv_geo.shp.csv', encoding = 'cp949', engine = 'python')
lv_geo.head(25)

,No,Unnamed: 1,No.1,store,address,경도,위도,상태
0,1,0,1,루이 비통 현대 목동점,서울특별시 양천구 목동동로 257,126.874619,37.527321,정좌표
1,2,1,2,루이 비통 현대 대구점,대구광역시 중구 달구벌대로 2077,128.590626,35.866630,정좌표
2,3,2,3,루이 비통 신세계 강남점 남성,서울특별시 서초구 신반포로 176,127.002794,37.504214,정좌표
3,4,3,4,루이 비통 현대 판교점,경기도 성남시 분당구 판교역로 146번길 20,127.112088,37.392795,정좌표
4,5,4,5,루이 비통 롯데호텔 제주,제주특별시 서귀포시 중문관광로 72번길 35,126.409242,33.249014,정좌표
5,6,5,6,루이 비통 신세계 본점 여성,서울특별시 중구 소공로 63,126.980978,37.560917,정좌표
6,7,6,7,루이 비통 현대 본점,서울특별시 강남구 압구정로 165,127.027468,37.527366,정좌표
7,8,7,8,루이 비통 스타필드 하남,경기도 하남시 미사대로 750,127.223741,37.545436,정좌표
8,9,8,9,루이 비통 신세계 경기점,경기도 용인시 수지구 포은대로 536,127.108106,37.325003,정좌표
9,10,9,10,루이 비통 현대 무역센터점 여성,서울특별시 강남구 테헤란로 517,127.059765,37.508615,정좌표
10,11,10,11,루이 비통 롯데 부산 서면점 남성,부산광역시 부산 진구 가야대로 772,129.057175,35.156676,정좌표
11,12,11,12,루이 비통 신세계 타임스퀘어점,서울특별시 영등포구 영등포동 영중로 15,126.904378,37.516872,정좌표
12,13,12,13,루이 비통 롯데 잠실점 여성,서울특별시 송파구 올림픽로 300,127.102719,37.512508,정좌표
13,14,13,14,루이 비통 현대 울산점,울산광역시 남구 삼산로 261,129.335812,35.539570,정좌표
14,15,14,15,루이 비통 갤러리아 남성,서울특별시 강남구 압구정로 343,127.040053,37.528476,정좌표
15,16,15,16,루이 비통 신세계 대구점,대구광역시 동구 동부로 149,128.629190,35.877941,정좌표
16,17,16,17,루이 비통 갤러리아 타임월드 대전점,대전광역시 서구 대덕대로 211,127.378167,36.351955,정좌표
17,18,17,18,루이 비통 롯데 인천 터미널점,인천광역시 남구 연남로 35,126.702082,37.439869,정좌표
18,19,18,19,루이 비통 메종 서울,서울특별시 강남구 압구정로 454,127.046226,37.525613,정좌표
19,20,19,20,루이 비통 롯데 에비뉴엘 여성,서울특별시 중구 남대문로 73,126.981638,37.564204,정좌표
20,21,20,21,루이 비통 신세계 광주점 여성,광주광역시 서구 광천동 49-1,126.880151,35.160297,정좌표
21,22,21,22,루이 비통 신세계 부산 센텀시티점 남성,부산광역시 해운대구 센텀남대로 35,129.129523,35.168818,정좌표

In [6]:
map_lv = folium.Map(location = [36.7219941, 127.4959787], tiles = 'cartodbpositron', zoom_start = 6)

In [7]:
for i, store in lv_geo.iterrows():
    folium.Marker(location = [store['위도'], store['경도']],
                  tooltip = store['store'],
                  icon = folium.Icon(color = 'beige', icon_color = 'darkred', icon = 'gift', prefix = 'fa')).add_to(map_lv)

map_lv.save('map_lv.html')
map_lv

In [8]:
#chanel
chanel_geo = pd.read_csv('chanel_geo.shp.csv', encoding = 'cp949', engine = 'python')
chanel_geo.head()

,No,Unnamed: 1,No.1,store,address,경도,위도,상태
0,1,0,1,롯데호텔면세점 샤넬 부티크,서울특별시 중구 을지로 30,126.981008,37.565346,정좌표
1,2,1,2,에비뉴엘 샤넬 부티크,서울특별시 중구 남대문로 73,126.981638,37.564204,정좌표
2,3,2,3,신세계백화점 본점 샤넬 부티크,서울특별시 소공로 63,126.980978,37.560917,정좌표
3,4,3,4,신세계면세점 명동점 샤넬 부티크,서울특별시 퇴계로 77,126.980776,37.560360,정좌표
4,5,4,5,신라면세점 서울점 샤넬 부티크,서울특별시 동호로 249,127.007955,37.557509,정좌표

In [9]:
map_chanel = folium.Map(location = [36.7219941, 127.4959787], tiles = 'cartodbpositron', zoom_start = 6)

In [10]:
for i, store in chanel_geo.iterrows():
    folium.Marker(location = [store['위도'], store['경도']],
                  tooltip = store['store'],
                  icon = folium.Icon(color = 'darkblue', icon_color = 'lightblue', icon = 'gift', prefix = 'fa')).add_to(map_chanel)

map_chanel.save('map_chanel.html')
map_chanel

In [40]:
#christian dior
cd_geo = pd.read_csv('cd_geo.shp.csv', encoding = 'cp949', engine = 'python')
cd_geo.head(25)

,No,Unnamed: 1,No.1,store,address,경도,위도,상태
0,1,0,1,Seoul House of DIOR,서울특별시 강남구 압구정로 464,127.046504,37.524786,정좌표
1,2,1,2,디올 성수,서울특별시 성동구 연무장5길 7,127.051983,37.543779,정좌표
2,3,2,3,디올 신세계 본점 여성,서울특별시 중구 소공로 63,126.980978,37.560917,정좌표
3,4,3,4,디올 갤러리아 남성,서울특별시 강남구 압구정로 343,127.040053,37.528476,정좌표
4,5,4,5,디올 신세계 강남,서울특별시 서초구 신반포로 176,127.002794,37.504214,정좌표
5,6,5,6,디올 제2 롯데월드,서울특별시 송파구 올림픽로 300,127.102719,37.512508,정좌표
6,7,6,7,디올 롯데 본점,서울특별시 중구 을지로 30,126.981008,37.565346,정좌표
7,8,7,8,디올 현대 본점,서울특별시 강남구 압구정로 165,127.027468,37.527366,정좌표
8,9,8,9,디올 롯데 부산,부산광역시 부산진구 가야대로 772,129.057175,35.156676,정좌표
9,10,9,10,디올 신세계 대구,대구광역시 동구 동부로 149,128.629190,35.877941,정좌표
10,11,10,11,디올 신세계 센텀시티 여성,부산광역시 해운대구 센텀남대로 35,129.129523,35.168818,정좌표
11,12,11,12,디올 신세계 광주,광주광역시 서구 무진대로 932,126.882598,35.160587,정좌표
12,13,12,13,디올 갤러리아 광교,수원시 영통구 광교중앙로 124,127.057264,37.285305,정좌표
13,14,13,14,디올 갤러리아 여성,서울특별시 강남구 압구정로 407,127.041832,37.527918,정좌표

In [12]:
map_cd = folium.Map(location = [36.7219941, 127.4959787], tiles = 'cartodbpositron', zoom_start = 6)

In [13]:
for i, store in cd_geo.iterrows():
    folium.Marker(location = [store['위도'], store['경도']],
                  tooltip = store['store'],
                  icon = folium.Icon(color = 'lightgray', icon_color = 'cadetblue', icon = 'gift', prefix = 'fa')).add_to(map_cd)

map_cd.save('map_cd.html')
map_cd

In [14]:
help(folium.Icon)

Help on class Icon in module folium.map:

class Icon(branca.element.MacroElement)
 |  Icon(color='blue', icon_color='white', icon='info-sign', angle=0, prefix='glyphicon', **kwargs)
 |
 |  Creates an Icon object that will be rendered
 |  using Leaflet.awesome-markers.
 |
 |  Parameters
 |  ----------
 |  color : str, default 'blue'
 |      The color of the marker. You can use:
 |
 |          ['red', 'blue', 'green', 'purple', 'orange', 'darkred',
 |           'lightred', 'beige', 'darkblue', 'darkgreen', 'cadetblue',
 |           'darkpurple', 'white', 'pink', 'lightblue', 'lightgreen',
 |           'gray', 'black', 'lightgray']
 |
 |  icon_color : str, default 'white'
 |      The color of the drawing on the marker. You can use colors above,
 |      or an html color code.
 |  icon : str, default 'info-sign'
 |      The name of the marker sign.
 |      See Font-Awesome website to choose yours.
 |      Warning : depending on the icon you choose you may need to adapt
 |      the `prefix` as well.
 |  angle : int, default 0
 |      The icon will be rotated by this amount of degrees.
 |  prefix : str, default 'glyphicon'
 |      The prefix states the source of the icon. 'fa' for font-awesome or
 |      'glyphicon' for bootstrap 3.
 |
 |  https://github.com/lvoogdt/Leaflet.awesome-markers
 |
 |  Method resolution order:
 |      Icon
 |      branca.element.MacroElement
 |      branca.element.Element
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, color='blue', icon_color='white', icon='info-sign', angle=0, prefix='glyphicon', **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  color_options = {'beige', 'black', 'blue', 'cadetblue', 'darkblue', 'd...
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from branca.element.MacroElement:
 |
 |  render(self, **kwargs)
 |      Renders the HTML representation of the element.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from branca.element.Element:
 |
 |  add_child(self, child, name=None, index=None)
 |      Add a child.
 |
 |  add_children(self, child, name=None, index=None)
 |      Add a child.
 |
 |  add_to(self, parent, name=None, index=None)
 |      Add element to a parent.
 |
 |  get_bounds(self)
 |      Computes the bounds of the object and all it's children
 |      in the form [[lat_min, lon_min], [lat_max, lon_max]].
 |
 |  get_name(self)
 |      Returns a string representation of the object.
 |      This string has to be unique and to be a python and
 |      javascript-compatible
 |      variable name.
 |
 |  get_root(self)
 |      Returns the root of the elements tree.
 |
 |  save(self, outfile, close_file=True, **kwargs)
 |      Saves an Element into a file.
 |
 |      Parameters
 |      ----------
 |      outfile : str or file object
 |          The file (or filename) where you want to output the html.
 |      close_file : bool, default True
 |          Whether the file has to be closed after write.
 |
 |  to_dict(self, depth=-1, ordered=True, **kwargs)
 |      Returns a dict representation of the object.
 |
 |  to_json(self, depth=-1, **kwargs)
 |      Returns a JSON representation of the object.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from branca.element.Element:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)

In [22]:
print(hermes_geo.shape)
print(lv_geo.shape)
print(chanel_geo.shape)
print(cd_geo.shape)

(18, 8)
(22, 8)
(14, 8)
(14, 8)

In [35]:
hermes_city = pd.DataFrame(hermes_geo['address'].apply(lambda v: v.split()[:1]).tolist(), columns = ['city'])
hermes_city['city'].value_counts()

서울특별시      12
인천광역시       2
부산광역시       2
제주특별자치도     1
대구광역시       1
Name: city, dtype: int64

In [42]:
lv_city = pd.DataFrame(lv_geo['address'].apply(lambda v: v.split()[:1]).tolist(), columns = ['city'])
lv_city[lv_city['city'] == '경기도']
lv_city.iloc[3] = ['성남시']
lv_city.iloc[7] = ['하남시']
lv_city.iloc[8] = ['용인시']
lv_city['city'].value_counts()

서울특별시    10
대구광역시     2
부산광역시     2
성남시       1
제주특별시     1
하남시       1
용인시       1
울산광역시     1
대전광역시     1
인천광역시     1
광주광역시     1
Name: city, dtype: int64

In [43]:
chanel_city = pd.DataFrame(chanel_geo['address'].apply(lambda v: v.split()[:1]).tolist(), columns = ['city'])
chanel_city['city'].value_counts()

서울특별시    10
부산광역시     2
인천광역시     1
대구광역시     1
Name: city, dtype: int64

In [44]:
cd_city = pd.DataFrame(cd_geo['address'].apply(lambda v: v.split()[:1]).tolist(), columns = ['city'])
cd_city['city'].value_counts()

서울특별시    9
부산광역시    2
대구광역시    1
광주광역시    1
수원시      1
Name: city, dtype: int64

In [47]:
print('hermes :', 18/5)
print('louis vuitton :', 22/11)
print('chanel :', 14/4)
print('christian dior :', 14/5)

hermes : 3.6
louis vuitton : 2.0
chanel : 3.5
christian dior : 2.8